project_id = "yazmxlgfraauuhmsnysh"

[functions.generate-html]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.update-payment-method]
verify_jwt = true

[functions.change-plan]
verify_jwt = true

[functions.transparent-checkout]
verify_jwt = true

[functions.sync-pending-payments]
verify_jwt = false

[functions.validate-test-cards]
verify_jwt = false

[functions.check-webhook-config]
verify_jwt = false